// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"];
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

    const mockSettingsBuilder = {
      select: () => mockSettingsBuilder,
      eq: () => mockSettingsBuilder,
      maybeSingle: async () => ({
        data: {
          user_id: "demo-admin-id",
          email_enabled: false,
          email_address: null,
          wa_enabled: false,
          wa_number: null,
          wa_api_key: null,
          notify_new: true,
          notify_status: true,
          notify_notes: true,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        error: null,
      }),
    };
    const mockSupabase = {
      from: () => mockSettingsBuilder,
    };

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.warn(
        "[Supabase Middleware] Missing SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY — running in mock auth mode",
      );
      return next({
        context: {
          supabase: mockSupabase as unknown as ReturnType<typeof createClient<Database>>,
          userId: "demo-admin-id",
          claims: { sub: "demo-admin-id", email: "admin@salutemalang.com" },
        },
      });
    }

    const request = getRequest();

    if (!request?.headers) {
      return next({
        context: {
          supabase: mockSupabase as unknown as ReturnType<typeof createClient<Database>>,
          userId: "demo-admin-id",
          claims: { sub: "demo-admin-id", email: "admin@salutemalang.com" },
        },
      });
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader || authHeader.includes("mock-access-token")) {
      return next({
        context: {
          supabase: mockSupabase as unknown as ReturnType<typeof createClient<Database>>,
          userId: "demo-admin-id",
          claims: { sub: "demo-admin-id", email: "admin@salutemalang.com" },
        },
      });
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token || token.split(".").length !== 3) {
      return next({
        context: {
          supabase: mockSupabase as unknown as ReturnType<typeof createClient<Database>>,
          userId: "demo-admin-id",
          claims: { sub: "demo-admin-id", email: "admin@salutemalang.com" },
        },
      });
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
