// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = (import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"]) as
    string | undefined;
  const SUPABASE_PUBLISHABLE_KEY = (import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["SUPABASE_PUBLISHABLE_KEY"]) as string | undefined;

  const hasCredentials = Boolean(
    SUPABASE_URL &&
    SUPABASE_PUBLISHABLE_KEY &&
    !SUPABASE_URL.includes("placeholder") &&
    SUPABASE_URL.startsWith("http"),
  );

  if (!hasCredentials) {
    console.warn(
      "[AI Studio] Supabase credentials not set — using local in-memory fallback client",
    );
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

function createMockSupabaseClient(): ReturnType<typeof createClient<Database>> {
  const STORAGE_KEY_ITEMS = "content_matrix_items_data_v1";
  const STORAGE_KEY_SETTINGS = "content_matrix_notif_settings_v1";
  const STORAGE_KEY_AUTH = "content_matrix_auth_session_v1";

  const defaultUser = {
    id: "demo-admin-id",
    email: "admin@salutemalang.com",
    user_metadata: { display_name: "Admin Salute Malang" },
    aud: "authenticated",
    created_at: new Date().toISOString(),
    app_metadata: {},
  };

  const defaultSession = {
    access_token: "mock-access-token-salute-malang",
    token_type: "bearer",
    expires_in: 3600,
    refresh_token: "mock-refresh-token",
    user: defaultUser,
  };

  const defaultItems = [
    {
      id: "item-1",
      user_id: "demo-admin-id",
      page: "Beranda",
      subpage: null,
      section: "1. Hero Banner",
      konten_text:
        "Jelajahi Pesona Malang & Bromo Bersama Salute Malang — Layanan Tour & Transport Terbaik dan Terpercaya di Jawa Timur.",
      media_url: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272",
      cta_text: "Pesan Sekarang",
      cta_link: "https://wa.me/6281234567890",
      referensi: "https://salutemalang.com",
      screenshot_mobile: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c",
      screenshot_desktop: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
      status: "Final",
      notes: "Foto latar dan copywriting sudah disetujui client.",
      created_at: "2026-09-01T08:00:00.000Z",
      updated_at: "2026-09-01T08:00:00.000Z",
    },
    {
      id: "item-2",
      user_id: "demo-admin-id",
      page: "Paket Tour",
      subpage: "Bromo Sunrise",
      section: "2. Fasilitas & Jadwal Trip",
      konten_text:
        "Paket Midnight Bromo: Jeep 4x4, Tiket Masuk Taman Nasional Bromo Tengger Semeru, Driver ramah merangkap Guide, Dokumentasi Foto & Video.",
      media_url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa",
      cta_text: "Lihat Jadwal",
      cta_link: "/paket-tour/bromo",
      referensi: "Instagram @salutemalang",
      screenshot_mobile: null,
      screenshot_desktop: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
      status: "Review",
      notes: "Menunggu konfirmasi harga tiket weekend terbaru.",
      created_at: "2026-09-02T09:30:00.000Z",
      updated_at: "2026-09-02T09:30:00.000Z",
    },
    {
      id: "item-3",
      user_id: "demo-admin-id",
      page: "Kontak",
      subpage: null,
      section: "3. Form Konsultasi & CS",
      konten_text:
        "Hubungi tim customer service Salute Malang untuk custom itinerary dan penawaran rombongan keluarga atau corporate gathering.",
      media_url: null,
      cta_text: "Hubungi Kami",
      cta_link: "https://wa.me/6281234567890",
      referensi: null,
      screenshot_mobile: null,
      screenshot_desktop: null,
      status: "Draft",
      notes: "Perlu verifikasi nomor WhatsApp CS operasional.",
      created_at: "2026-09-03T10:15:00.000Z",
      updated_at: "2026-09-03T10:15:00.000Z",
    },
  ];

  const getStored = <T>(key: string, fallback: T): T => {
    if (typeof window === "undefined") return fallback;
    try {
      const val = localStorage.getItem(key);
      return val ? (JSON.parse(val) as T) : fallback;
    } catch {
      return fallback;
    }
  };

  const setStored = (key: string, val: unknown) => {
    if (typeof window === "undefined") return;
    try {
      localStorage.setItem(key, JSON.stringify(val));
    } catch (e) {
      console.warn("Storage save error:", e);
    }
  };

  const authSubscribers = new Set<(event: string, session: unknown) => void>();

  const mockClient = {
    auth: {
      async getSession() {
        const session = getStored(STORAGE_KEY_AUTH, defaultSession);
        return { data: { session }, error: null };
      },
      async getUser() {
        const session = getStored(STORAGE_KEY_AUTH, defaultSession);
        return { data: { user: session ? session.user : null }, error: null };
      },
      onAuthStateChange(callback: (event: string, session: unknown) => void) {
        authSubscribers.add(callback);
        return {
          data: {
            subscription: {
              unsubscribe: () => {
                authSubscribers.delete(callback);
              },
            },
          },
        };
      },
      async signInWithPassword({ email }: { email: string; password?: string }) {
        const session = {
          ...defaultSession,
          user: {
            ...defaultUser,
            email: email || defaultUser.email,
          },
        };
        setStored(STORAGE_KEY_AUTH, session);
        authSubscribers.forEach((cb) => cb("SIGNED_IN", session));
        return { data: { user: session.user, session }, error: null };
      },
      async signOut() {
        setStored(STORAGE_KEY_AUTH, null);
        authSubscribers.forEach((cb) => cb("SIGNED_OUT", null));
        return { error: null };
      },
    },
    from(table: string) {
      if (table === "content_items") {
        return {
          select(_cols?: string) {
            const filters: ((item: Record<string, unknown>) => boolean)[] = [];
            let sortFn:
              ((a: Record<string, unknown>, b: Record<string, unknown>) => number) | null = null;

            const execute = () => {
              let list = getStored<Record<string, unknown>[]>(STORAGE_KEY_ITEMS, defaultItems);
              for (const f of filters) {
                list = list.filter(f);
              }
              if (sortFn) {
                list = [...list].sort(sortFn);
              }
              return { data: list, error: null };
            };

            const builder = {
              order(field: string, opts?: { ascending?: boolean }) {
                const asc = opts?.ascending !== false;
                sortFn = (a, b) => {
                  const valA = String(a[field] ?? "");
                  const valB = String(b[field] ?? "");
                  return asc ? valA.localeCompare(valB) : valB.localeCompare(valA);
                };
                return builder;
              },
              eq(field: string, val: unknown) {
                filters.push((item) => item[field] === val);
                return builder;
              },
              maybeSingle: async () => {
                const res = execute();
                return { data: res.data[0] ?? null, error: null };
              },
              then(
                onfulfilled?: (value: { data: Record<string, unknown>[]; error: null }) => unknown,
              ) {
                const res = execute();
                return Promise.resolve(res).then(onfulfilled);
              },
            };
            return builder;
          },
          async insert(payload: Record<string, unknown> | Record<string, unknown>[]) {
            const list = getStored<Record<string, unknown>[]>(STORAGE_KEY_ITEMS, defaultItems);
            const items = Array.isArray(payload) ? payload : [payload];
            const created = items.map((item) => ({
              id: item["id"] || `item-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
              ...item,
            }));
            const updatedList = [...list, ...created];
            setStored(STORAGE_KEY_ITEMS, updatedList);
            return { data: created, error: null };
          },
          update(payload: Record<string, unknown>) {
            return {
              eq(field: string, val: unknown) {
                const list = getStored<Record<string, unknown>[]>(STORAGE_KEY_ITEMS, defaultItems);
                const updatedList = list.map((item) =>
                  item[field] === val
                    ? { ...item, ...payload, updated_at: new Date().toISOString() }
                    : item,
                );
                setStored(STORAGE_KEY_ITEMS, updatedList);
                return Promise.resolve({ data: updatedList, error: null });
              },
            };
          },
          delete() {
            return {
              eq(field: string, val: unknown) {
                const list = getStored<Record<string, unknown>[]>(STORAGE_KEY_ITEMS, defaultItems);
                const updatedList = list.filter((item) => item[field] !== val);
                setStored(STORAGE_KEY_ITEMS, updatedList);
                return Promise.resolve({ data: null, error: null });
              },
            };
          },
        };
      }

      if (table === "notification_settings") {
        const defaultSettings = {
          webhook_enabled: false,
          webhook_url: "",
          notify_new: true,
          notify_status: true,
          notify_notes: true,
          user_id: "demo-admin-id",
        };

        return {
          select(_cols?: string) {
            return {
              maybeSingle: async () => {
                const settings = getStored(STORAGE_KEY_SETTINGS, defaultSettings);
                return { data: settings, error: null };
              },
              eq(_field: string, _val: unknown) {
                return {
                  maybeSingle: async () => {
                    const settings = getStored(STORAGE_KEY_SETTINGS, defaultSettings);
                    return { data: settings, error: null };
                  },
                };
              },
            };
          },
          async upsert(payload: Record<string, unknown>) {
            const prev = getStored(STORAGE_KEY_SETTINGS, defaultSettings);
            const merged = { ...prev, ...payload, updated_at: new Date().toISOString() };
            setStored(STORAGE_KEY_SETTINGS, merged);
            return { data: merged, error: null };
          },
        };
      }

      if (table === "profiles") {
        const STORAGE_KEY_PROFILES = "content_matrix_profiles_v1";
        const defaultProfiles = [
          {
            id: "demo-admin-id",
            display_name: "Admin Salute Malang",
            avatar_url: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
        ];

        return {
          select(_cols?: string) {
            return {
              order(field: string, opts?: { ascending?: boolean }) {
                return {
                  then(
                    onfulfilled?: (value: {
                      data: Record<string, unknown>[];
                      error: null;
                    }) => unknown,
                  ) {
                    const list = getStored<Record<string, unknown>[]>(
                      STORAGE_KEY_PROFILES,
                      defaultProfiles,
                    );
                    return Promise.resolve({ data: list, error: null }).then(onfulfilled);
                  },
                };
              },
              then(
                onfulfilled?: (value: { data: Record<string, unknown>[]; error: null }) => unknown,
              ) {
                const list = getStored<Record<string, unknown>[]>(
                  STORAGE_KEY_PROFILES,
                  defaultProfiles,
                );
                return Promise.resolve({ data: list, error: null }).then(onfulfilled);
              },
            };
          },
          async insert(payload: Record<string, unknown> | Record<string, unknown>[]) {
            const list = getStored<Record<string, unknown>[]>(
              STORAGE_KEY_PROFILES,
              defaultProfiles,
            );
            const items = Array.isArray(payload) ? payload : [payload];
            const created = items.map((item) => ({
              id: item["id"] || `profile-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
              ...item,
            }));
            const updatedList = [...list, ...created];
            setStored(STORAGE_KEY_PROFILES, updatedList);
            return { data: created, error: null };
          },
          delete() {
            return {
              eq(field: string, val: unknown) {
                const list = getStored<Record<string, unknown>[]>(
                  STORAGE_KEY_PROFILES,
                  defaultProfiles,
                );
                const updatedList = list.filter((item) => item[field] !== val);
                setStored(STORAGE_KEY_PROFILES, updatedList);
                return Promise.resolve({ data: null, error: null });
              },
            };
          },
        };
      }

      return {
        select: () => ({ maybeSingle: async () => ({ data: null, error: null }) }),
      };
    },
    storage: {
      from: (bucket: string) => ({
        upload: async (path: string, file: File) => {
          // Mock upload by creating a local object URL (in real app, we'd upload to supabase storage)
          const url = URL.createObjectURL(file);
          // Return the object URL as the path so getPublicUrl can identify and return it
          return { data: { path: url }, error: null };
        },
        getPublicUrl: (path: string) => {
          // Since we use object URLs in the mock, we need a way to pass the file around.
          // For a simple mock, we'll just assume the path is an object URL if it starts with blob:
          // or we just return a fake unsplash placeholder for demo purposes.
          if (path.startsWith("blob:")) {
            return { data: { publicUrl: path } };
          }
          // fallback placeholder
          return {
            data: { publicUrl: `https://images.unsplash.com/photo-1460925895917-afdab827c52f` },
          };
        },
      }),
    },
  };

  return mockClient as unknown as ReturnType<typeof createClient<Database>>;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
